import { NERState } from '../types';

export const NER_STATES: NERState[] = [
  {
    code: 'ML',
    name: 'Meghalaya',
    capital: 'Shillong',
    latitude: 25.5788,
    longitude: 91.8933,
    deocContact: '0364-2502094',
    sdrfContact: '1070',
    districts: [
      {
        id: 'ekh',
        name: 'East Khasi Hills (Shillong)',
        state: 'Meghalaya',
        latitude: 25.5788,
        longitude: 91.8933,
        baselineSusceptibility: 'Very High',
        majorRoads: ['NH-6', 'Shillong Bypass', 'Sohra Road'],
      },
      {
        id: 'sohra',
        name: 'Cherrapunji (Sohra)',
        state: 'Meghalaya',
        latitude: 25.2986,
        longitude: 91.7086,
        baselineSusceptibility: 'Very High',
        majorRoads: ['SH-5', 'Sohra-Shella Road'],
      },
      {
        id: 'wgh',
        name: 'West Garo Hills (Tura)',
        state: 'Meghalaya',
        latitude: 25.5141,
        longitude: 90.2033,
        baselineSusceptibility: 'High',
        majorRoads: ['NH-217', 'Tura-Dalu Road'],
      },
      {
        id: 'ribhoi',
        name: 'Ri-Bhoi (Nongpoh)',
        state: 'Meghalaya',
        latitude: 25.9036,
        longitude: 91.8809,
        baselineSusceptibility: 'High',
        majorRoads: ['NH-6 Corridor'],
      },
    ],
  },
  {
    code: 'AS',
    name: 'Assam',
    capital: 'Dispur / Guwahati',
    latitude: 26.1445,
    longitude: 91.7362,
    deocContact: '0361-2237221',
    sdrfContact: '1070',
    districts: [
      {
        id: 'dima_hasao',
        name: 'Dima Hasao (Haflong)',
        state: 'Assam',
        latitude: 25.1834,
        longitude: 93.0232,
        baselineSusceptibility: 'Very High',
        majorRoads: ['NH-27', 'Lumding-Badarpur Line'],
      },
      {
        id: 'kamrup',
        name: 'Kamrup Metropolitan (Guwahati)',
        state: 'Assam',
        latitude: 26.1445,
        longitude: 91.7362,
        baselineSusceptibility: 'High',
        majorRoads: ['NH-27', 'NH-37'],
      },
      {
        id: 'cachar',
        name: 'Cachar (Silchar)',
        state: 'Assam',
        latitude: 24.8333,
        longitude: 92.7789,
        baselineSusceptibility: 'High',
        majorRoads: ['NH-37', 'NH-306'],
      },
      {
        id: 'karbi',
        name: 'Karbi Anglong (Diphu)',
        state: 'Assam',
        latitude: 25.8447,
        longitude: 93.4332,
        baselineSusceptibility: 'High',
        majorRoads: ['NH-36', 'NH-329'],
      },
    ],
  },
  {
    code: 'MZ',
    name: 'Mizoram',
    capital: 'Aizawl',
    latitude: 23.7271,
    longitude: 92.7176,
    deocContact: '0389-2399222',
    sdrfContact: '1070',
    districts: [
      {
        id: 'aizawl',
        name: 'Aizawl',
        state: 'Mizoram',
        latitude: 23.7271,
        longitude: 92.7176,
        baselineSusceptibility: 'Very High',
        majorRoads: ['NH-54', 'Durtlang Ridge Road'],
      },
      {
        id: 'lunglei',
        name: 'Lunglei',
        state: 'Mizoram',
        latitude: 22.8872,
        longitude: 92.7381,
        baselineSusceptibility: 'High',
        majorRoads: ['NH-54 South', 'SH-2'],
      },
      {
        id: 'champhai',
        name: 'Champhai',
        state: 'Mizoram',
        latitude: 23.4735,
        longitude: 93.3297,
        baselineSusceptibility: 'High',
        majorRoads: ['NH-6 Link'],
      },
    ],
  },
  {
    code: 'NL',
    name: 'Nagaland',
    capital: 'Kohima',
    latitude: 25.6751,
    longitude: 94.1086,
    deocContact: '0370-2291122',
    sdrfContact: '1070',
    districts: [
      {
        id: 'kohima',
        name: 'Kohima',
        state: 'Nagaland',
        latitude: 25.6751,
        longitude: 94.1086,
        baselineSusceptibility: 'Very High',
        majorRoads: ['NH-29', 'Kohima-Mao Highway'],
      },
      {
        id: 'dimapur',
        name: 'Dimapur',
        state: 'Nagaland',
        latitude: 25.9094,
        longitude: 93.7265,
        baselineSusceptibility: 'Moderate',
        majorRoads: ['NH-29', 'NH-39'],
      },
      {
        id: 'mokokchung',
        name: 'Mokokchung',
        state: 'Nagaland',
        latitude: 26.3255,
        longitude: 94.5165,
        baselineSusceptibility: 'High',
        majorRoads: ['NH-702'],
      },
    ],
  },
  {
    code: 'SK',
    name: 'Sikkim',
    capital: 'Gangtok',
    latitude: 27.3389,
    longitude: 88.6065,
    deocContact: '03592-202222',
    sdrfContact: '1070',
    districts: [
      {
        id: 'gangtok',
        name: 'Gangtok',
        state: 'Sikkim',
        latitude: 27.3389,
        longitude: 88.6065,
        baselineSusceptibility: 'Very High',
        majorRoads: ['NH-10 (Teesta Corridor)', 'Indira Bypass'],
      },
      {
        id: 'mangan',
        name: 'Mangan (North Sikkim)',
        state: 'Sikkim',
        latitude: 27.5054,
        longitude: 88.5332,
        baselineSusceptibility: 'Very High',
        majorRoads: ['North Sikkim Highway', 'Chungthang Road'],
      },
      {
        id: 'namchi',
        name: 'Namchi (South Sikkim)',
        state: 'Sikkim',
        latitude: 27.1667,
        longitude: 88.35,
        baselineSusceptibility: 'High',
        majorRoads: ['Jorethang-Namchi Road'],
      },
    ],
  },
  {
    code: 'AR',
    name: 'Arunachal Pradesh',
    capital: 'Itanagar',
    latitude: 27.0844,
    longitude: 93.6053,
    deocContact: '0360-2212222',
    sdrfContact: '1070',
    districts: [
      {
        id: 'itanagar',
        name: 'Papum Pare (Itanagar)',
        state: 'Arunachal Pradesh',
        latitude: 27.0844,
        longitude: 93.6053,
        baselineSusceptibility: 'High',
        majorRoads: ['NH-415', 'Trans-Arunachal Highway'],
      },
      {
        id: 'tawang',
        name: 'Tawang',
        state: 'Arunachal Pradesh',
        latitude: 27.5861,
        longitude: 91.8594,
        baselineSusceptibility: 'Very High',
        majorRoads: ['Bhalukpong-Tawang Highway', 'Sela Pass Road'],
      },
      {
        id: 'west_kameng',
        name: 'West Kameng (Bomdila)',
        state: 'Arunachal Pradesh',
        latitude: 27.2644,
        longitude: 92.4222,
        baselineSusceptibility: 'Very High',
        majorRoads: ['NH-13'],
      },
    ],
  },
  {
    code: 'MN',
    name: 'Manipur',
    capital: 'Imphal',
    latitude: 24.817,
    longitude: 93.9368,
    deocContact: '0385-2451122',
    sdrfContact: '1070',
    districts: [
      {
        id: 'imphal_west',
        name: 'Imphal West',
        state: 'Manipur',
        latitude: 24.817,
        longitude: 93.9368,
        baselineSusceptibility: 'Moderate',
        majorRoads: ['NH-2', 'NH-37'],
      },
      {
        id: 'tamenglong',
        name: 'Tamenglong',
        state: 'Manipur',
        latitude: 24.9833,
        longitude: 93.4833,
        baselineSusceptibility: 'Very High',
        majorRoads: ['Imphal-Jiribam Road (NH-37)', 'Tupul Railway Cut'],
      },
      {
        id: 'churachandpur',
        name: 'Churachandpur',
        state: 'Manipur',
        latitude: 24.3333,
        longitude: 93.6833,
        baselineSusceptibility: 'High',
        majorRoads: ['Tiddim Road (NH-102B)'],
      },
    ],
  },
  {
    code: 'TR',
    name: 'Tripura',
    capital: 'Agartala',
    latitude: 23.8315,
    longitude: 91.2868,
    deocContact: '0381-2411122',
    sdrfContact: '1070',
    districts: [
      {
        id: 'west_tripura',
        name: 'West Tripura (Agartala)',
        state: 'Tripura',
        latitude: 23.8315,
        longitude: 91.2868,
        baselineSusceptibility: 'Moderate',
        majorRoads: ['NH-8 Lifeline'],
      },
      {
        id: 'dhalai',
        name: 'Dhalai (Ambassa)',
        state: 'Tripura',
        latitude: 23.9167,
        longitude: 91.85,
        baselineSusceptibility: 'High',
        majorRoads: ['NH-8 Hill Section', 'Baramura Hills Cut'],
      },
    ],
  },
];

export const NER_CENTER = {
  latitude: 25.5788,
  longitude: 91.8933,
  latitudeDelta: 3.5,
  longitudeDelta: 3.5,
};

export const EMERGENCY_NUMBERS = {
  nationalEmergency: '112',
  disasterManagement: '1070',
  ambulance: '108',
  fire: '101',
  police: '100',
  broControlRoom: '0364-2537233',
  nerDisasterCell: '1800-345-3850',
};

export const OFFICIAL_DISCLAIMER =
  'Giri Raksha is a prototype decision-support system. Risk estimates are model-based and should not replace official disaster-management advisories.';
